In [2]:
#Thư viện Numpy
import numpy as np
vec1 = np.array([1., 3., 5.])
vec1 * 2
#Kết quả: array([ 2.,  6., 10.])
vec1 * vec1
#Kết quả: array([ 1.,  9., 25.])
vec1 / 2
#Kết quả: array([0.5, 1.5, 2.5])
vec1 + vec1
# Kết quả: array([ 2.,  6., 10.])
vec2 = np.array([2., 4.])
vec1 + vec2
#Kết quả: Lỗi
vec3 = np.array([2., 4., 6.])
vec1 + vec3
#Kết quả: array([ 3.,  7., 11.])
vec1 / vec3
#Kết quả: array([0.5 , 0.75, 0.83333333])
vec1 * vec3
#Kết quả: array([ 2., 12., 30.])
2 * vec1 + 5 * vec3
#Kết quả: array([12., 26., 40.])
vec3[2]
#Kết quả: 6.0
vec4 = np.linspace(0, 20, 5)
vec4
#Kết quả: array([ 0.,  5., 10., 15., 20.])
vec5 = np.zeros(5)
#Kết quả: array([0., 0., 0., 0., 0.])
vec6 = np.ones(5)
#Kết quả: array([1., 1., 1., 1., 1.])
vec7 = np.empty(5)
#Kết quả: array([...])
np.random.random(5)
#Kết quả: array([...])


array([ 2.,  6., 10.])

In [ ]:
import numpy as np
v = np.array([1., 3., 5.])
np.sum(v)
#Kết quả: 9.0
v.shape
#Kết quả: (3,)
v.transpose()
#Kết quả: array([1., 3., 5.])
v1 = v[:2]
v1
#Kết quả: array([1., 3.])
v[0] = 5
v
# Kết quả: array([5., 3., 5.])
v1
# Kết quả: array([5., 3.])
v1[:2] = [1., 2]
v
# Kết quả: array([1., 2., 5.])
v3 = 2 * v[:2] + v1 * 3
v3
#Kết quả: array([5., 10.])
v1 = [4, 6]
v3
#Kết quả vẫn: array([5., 10.])
v
#Kết quả: array([1., 2., 5.])
v + 10.0
#Kết quả: array([11., 12., 15.])
np.sqrt(v)
#Kết quả: array([1.        , 1.41421356, 2.23606798])
np.cos(v)
#Kết quả: array([ 0.54030231, -0.41614684,  0.28366219])
np.sin(v)
#Kết quả: array([0.84147098, 0.90929743, 0.95892427])


In [3]:
#bai 1
from sympy import Symbol, solve
x = Symbol('x')
bieuthuc = x + 3 - 5
print(solve(bieuthuc))
bieuthuc = x**2 + 3 - 5
nghiemx = solve(bieuthuc)
print(nghiemx)        # Toàn bộ nghiệm
print(nghiemx[0])     # Nghiệm thứ nhất
print(nghiemx[1])     # Nghiệm thứ hai

[2]
[-sqrt(2), sqrt(2)]
-sqrt(2)
sqrt(2)


In [4]:
#bai 2
from sympy import Symbol, solve
x = Symbol('x')
ptb2 = x**2 + 9*x + 8
nghiem = solve(ptb2, dict=True)
print(nghiem)
ptb2 = x**2 + x + 10
nghiemx = solve(ptb2, dict=True)
print(nghiemx)


[{x: -8}, {x: -1}]
[{x: -1/2 - sqrt(39)*I/2}, {x: -1/2 + sqrt(39)*I/2}]


In [ ]:
#bai 3
from sympy import Symbol, solve
# Khai báo các biến symbol
x = Symbol('x')
a = Symbol('a')
b = Symbol('b')
c = Symbol('c')
# Định nghĩa phương trình bậc 2 tổng quát
ptb2 = a*x**2 + b*x + c
# Giải phương trình theo biến x, kết quả dạng dict
nghiem = solve(ptb2, x, dict=True)
# In kết quả
print(nghiem)


In [ ]:
#bai 4
from sympy import Symbol, solve
# Khai báo biến
x = Symbol('x')
y = Symbol('y')
# Định nghĩa hai phương trình
pt1 = 2*x + 3*y - 12
pt2 = 3*x - 2*y - 5
# Giải hệ phương trình, trả kết quả dạng dict
nghiem = solve((pt1, pt2), dict=True)
# In kết quả nghiệm
print(nghiem)
# Lấy nghiệm đầu tiên trong danh sách nghiệm
nghiem_1 = nghiem[0]
# Thay nghiệm vào từng phương trình để kiểm tra
kiemtra1 = pt1.subs({x: nghiem_1[x], y: nghiem_1[y]})
kiemtra2 = pt2.subs({x: nghiem_1[x], y: nghiem_1[y]})
# In kết quả kiểm tra
print("Giá trị pt1 sau khi thay:", kiemtra1)
print("Giá trị pt2 sau khi thay:", kiemtra2)


In [5]:
#bai 5
import numpy as np
# Ma trận M1
M1 = np.array([[9, 12], [23, 30]])
print("Ma trận M1:\n", M1)
# Vector u
u = np.array([2, 1])
# Tích M1.u
tichM1u = M1.dot(u)
print("M1.dot(u):", tichM1u)
# Giải thích: mỗi dòng của M1 nhân với vector u theo quy tắc nhân ma trận – vector
# [9*2 + 12*1 = 30, 23*2 + 30*1 = 76]
# Tích u.M1
tichuM1 = u.dot(M1)
print("u.dot(M1):", tichuM1)
# Giải thích: vector u nhân từng cột của M1 – kết quả khác chiều với M1.dot(u)
# [2*9 + 1*23 = 41, 2*12 + 1*30 = 54]
# Kiểm tra với np.dot
print("np.dot(M1, u):", np.dot(M1, u))
print("np.dot(u, M1):", np.dot(u, M1))
mat1 = np.zeros([5,5])
print("mat1 (ma trận toàn 0):\n", mat1)
mat2 = np.ones([5,5])
print("mat2 (ma trận toàn 1):\n", mat2)
mat3 = mat1 + 2 * mat2
print("mat3 = mat1 + 2 * mat2:\n", mat3)
# Mỗi phần tử của mat2 được nhân 2 rồi cộng với 0 -> ra ma trận toàn số 2
mat4 = mat3
mat3[3][2] = 10
print("mat3 sau khi đổi giá trị [3][2] = 10:\n", mat3)
print("mat4 có thay đổi theo mat3 không?:\n", mat4)
# Vì mat4 = mat3 là gán tham chiếu, nên cả 2 đều thay đổi
mat5 = np.copy(mat3)
mat3[3][2] = 20
print("mat3 sau khi đổi [3][2] = 20:\n", mat3)
print("mat5 có thay đổi theo không?:\n", mat5)
# mat5 là bản sao độc lập, không bị ảnh hưởng khi mat3 thay đổi


Ma trận M1:
 [[ 9 12]
 [23 30]]
M1.dot(u): [30 76]
u.dot(M1): [41 54]
np.dot(M1, u): [30 76]
np.dot(u, M1): [41 54]
mat1 (ma trận toàn 0):
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
mat2 (ma trận toàn 1):
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
mat3 = mat1 + 2 * mat2:
 [[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]
mat3 sau khi đổi giá trị [3][2] = 10:
 [[ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2. 10.  2.  2.]
 [ 2.  2.  2.  2.  2.]]
mat4 có thay đổi theo mat3 không?:
 [[ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2. 10.  2.  2.]
 [ 2.  2.  2.  2.  2.]]
mat3 sau khi đổi [3][2] = 20:
 [[ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2. 20.  2.  2.]
 [ 2.  2.  2.  2.  2.]]
mat5 có thay đổi theo không?:
 [[ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  

In [6]:
#bai 6
import numpy as np
# Ma trận nguy cơ theo từng yếu tố (5 yếu tố)
A = np.array([[1, 1, 0, 0, 1],
              [3, 0, 1, 1, 2],
              [2, 1, 0, 2, 3]])

B = np.array([[1, 2, 2, 1, 1],
              [2, 0, 1, 2, 2],
              [0, 1, 1, 1, 0]])

C = np.array([[0, 5, 1, 1, 1],
              [1, 1, 2, 1, 3],
              [0, 0, 1, 3, 2]])

D = np.array([[3, 1, 1, 0, 1],
              [5, 0, 0, 3, 7],
              [5, 0, 0, 3, 5]])

E = np.array([[0, 0, 0, 0, 0],
              [0, 0, 5, 10, 15],
              [20, 20, 5, 0, 0]])
def is_safe(matrix, threshold=5):
    """Trả về ma trận boolean thể hiện nơi an toàn (<= threshold)"""
    return matrix <= threshold
# a. Chiến dịch 1-2 ngày: chỉ xét lưới E (lộ bí mật)
a_risk = E
safe_a = is_safe(a_risk)
# b. Tập luyện thời bình: xét A (cháy rừng), B (lụ), C (sạt lở)
b_risk = A + B + C
safe_b = is_safe(b_risk)
# c. Mùa khô: bỏ B (lụ), C (sạt), giữ A, D
c_risk = A + D
safe_c = is_safe(c_risk)
# d. Mùa mưa: bỏ A (cháy rừng), dùng B, C, D
d_risk = B + C + D
safe_d = is_safe(d_risk)
# e. Tám tháng: xét đủ cả A+B+C+D+E
e_risk = A + B + C + D + E
safe_e = is_safe(e_risk)
def print_safe_positions(mask, label):
    print(f"\nVị trí an toàn cho kịch bản {label}:")
    print(mask.astype(int))  # 1 là an toàn, 0 là không
print_safe_positions(safe_a, "a - chiến dịch 1-2 ngày")
print_safe_positions(safe_b, "b - tập luyện thời bình")
print_safe_positions(safe_c, "c - mùa khô")
print_safe_positions(safe_d, "d - mùa mưa")
print_safe_positions(safe_e, "e - 8 tháng")



Vị trí an toàn cho kịch bản a - chiến dịch 1-2 ngày:
[[1 1 1 1 1]
 [1 1 1 0 0]
 [0 0 1 1 1]]

Vị trí an toàn cho kịch bản b - tập luyện thời bình:
[[1 0 1 1 1]
 [0 1 1 1 0]
 [1 1 1 0 1]]

Vị trí an toàn cho kịch bản c - mùa khô:
[[1 1 1 1 1]
 [0 1 1 1 0]
 [0 1 1 1 0]]

Vị trí an toàn cho kịch bản d - mùa mưa:
[[1 0 1 1 1]
 [0 1 1 0 0]
 [1 1 1 0 0]]

Vị trí an toàn cho kịch bản e - 8 tháng:
[[1 0 1 1 1]
 [0 1 0 0 0]
 [0 0 0 0 0]]
