In [1]:
#1 Dẫn nhập – Một số hàm về xử lý vector với Python
def scale(a, v):
    return [a * vi for vi in v]
def sumvector(v, w):
    return [vi + wi for (vi, wi) in zip(v, w)]
def dotvector(v, w):
    return sum([vi * wi for (vi, wi) in zip(v, w)])
def lenvector(v):
    return dotvector(v, v)
v = [3, 5, 7]
w = [2, 4, 6]
print("scale(10, v):", scale(10, v))
print("sumvector(v, w):", sumvector(v, w))
print("dotvector(v, w):", dotvector(v, w))
print("lenvector(w):", lenvector(w))


scale(10, v): [30, 50, 70]
sumvector(v, w): [5, 9, 13]
dotvector(v, w): 68
lenvector(w): 56


In [ ]:
#2 Bài toán ứng dụng 1 – Phân loại tuyến tính
import numpy as np
scores = np.array([-1, 1, 2, -3, 5, -4])
print("scores:", scores)
# Kiểm tra điều kiện >= 0
print("scores >= 0:", scores >= 0)
# Kiểm tra điều kiện < 0
print("scores < 0:", scores < 0)
# Phân loại theo 2 nhóm
labels_2 = np.select([scores >= 0, scores < 0], ['so duong', 'so am'])
print("Phân loại 2 nhóm:", labels_2)
# Phân loại 3 nhóm:
scores = np.array([-1, 1, 2, 0, -3, 5, 0, -4])
labels_3 = np.select([scores > 0, scores == 0, scores < 0], ['so duong', 'so 0', 'so am'])
print("scores:", scores)
print("Phân loại 3 nhóm:", labels_3)



In [14]:
#3.1) Cơ bản về xử lý ma trận
import numpy as np
from scipy import linalg, sparse
#1 Khai báo ma trận D
D = np.array([[3, 4], [5, 6]])
print("D =\n", D)

#2 Tạo ma trận C ngẫu nhiên
C = np.array(np.random.random((5, 7)))
print("C =\n", C)

#3 Tạo ma trận A ngẫu nhiên
A = np.array(np.random.random((2, 2)))
print("A =\n", A)

#4
b = np.array([(1 + 5j, 2j, 3j), (4, 5, 6)])
B = np.asmatrix(b)

#5 In b và B
print("b =\n", b)
print("B =\n", B)

#6 Chuyển vị ma trận A
print("A.T =\n", A.T)

#7 Ma trận nghịch đảo A
try:
    print("A nghịch đảo dùng A_inv =\n", np.linalg.inv(A))
    print("A nghịch đảo dùng linalg.inv =\n", linalg.inv(A))
except np.linalg.LinAlgError:
    print("Ma trận A không khả nghịch (det(A) = 0)")

#8 Ma trận dưới từ đường chéo
M = np.array([[-1, 3, 2], [0, -2, 1], [1, 5, -2]])
M_lower = np.tril(M)
print("M_lower =\n", M_lower)

#9 Ma trận trên từ đường chéo
M_upper = np.triu(M)
print("M_upper =\n", M_upper)

#10 Vector và ma trận đường chéo
v_diag = np.diag(M)
print("Vector đường chéo v_diag =\n", v_diag)
M_diag = np.diag(v_diag)
print("Ma trận đường chéo M_diag =\n", M_diag)

D =
 [[3 4]
 [5 6]]
C =
 [[0.44654724 0.66730162 0.4214053  0.63670809 0.6314737  0.56093001
  0.59965456]
 [0.72300383 0.27962444 0.74970326 0.32368636 0.02349244 0.06352389
  0.26051705]
 [0.76085176 0.4807061  0.57712504 0.45448825 0.79453518 0.66977648
  0.73603746]
 [0.58561548 0.86223656 0.31558392 0.9397675  0.04116665 0.33705549
  0.16547378]
 [0.21487498 0.1900601  0.9097449  0.84782099 0.93038369 0.62795328
  0.69850775]]
A =
 [[0.77152214 0.24780819]
 [0.35699656 0.03690526]]
b =
 [[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]
B =
 [[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]
A.T =
 [[0.77152214 0.35699656]
 [0.24780819 0.03690526]]
A nghịch đảo dùng A_inv =
 [[ -0.61515499   4.13058801]
 [  5.95059305 -12.86010804]]
A nghịch đảo dùng linalg.inv =
 [[ -0.61515499   4.13058801]
 [  5.95059305 -12.86010804]]
M_lower =
 [[-1  0  0]
 [ 0 -2  0]
 [ 1  5 -2]]
M_upper =
 [[-1  3  2]
 [ 0 -2  1]
 [ 0  0 -2]]
Vector đường chéo v_diag =
 [-1 -2 -2]
Ma trận đường chéo M_diag =
 [

In [17]:
#3.2
import numpy as np
np.set_printoptions(precision=2, suppress=True)
A = np.reshape(np.arange(36.0), (6, 6))
print("Ma trận A:")
print(A)
I6 = np.identity(6)
print("\nMa trận đơn vị I6:")
print(I6)
print("\nKích thước của A (số phần tử):", A.size)
print("\nĐường chéo chính của A:", np.diagonal(A))
A = A + I6
print("\nMa trận A sau khi cộng với I6:")
print(A)
np.set_printoptions(precision=2, suppress=True)
# Tạo ma trận A
A = np.reshape(np.arange(36.0), (6, 6)) + np.identity(6)

# Vector vecB
vecB = np.array([1., 2., 3., 4., 5., 6.])
C = A.dot(vecB)
print("vecB =")
print(vecB)
print("\nC = A × vecB:")
print(C)

# Khai báo ma trận D
D = np.array([[1., 2., 3., 4., 5., 6.], [1., 0., 1., 0., 1., 0.]])
print("\nMa trận D:")
print(D)
E = A.dot(D.T)
print("\nE = A × D.T:")
print(E)
# Khai báo ma trận F (6x2)
F = np.array([
    [1., 1.],
    [2., 0.],
    [3., 1.],
    [4., 0.],
    [5., 1.],
    [6., 0.]
])
print("\nMa trận F:")
print(F)
G = A.dot(F)
print("\nG = A × F:")
print(G)
A_inv = np.linalg.inv(A)
print("\nMa trận nghịch đảo A⁻¹:")
print(A_inv)
A_double_inv = np.linalg.inv(np.linalg.inv(A))
print("\nnp.linalg.inv(np.linalg.inv(A)):")
print(A_double_inv)
print("\nA ≈ inv(inv(A))", np.allclose(A, A_double_inv))

Ma trận A:
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]

Ma trận đơn vị I6:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

Kích thước của A (số phần tử): 36

Đường chéo chính của A: [ 0.  7. 14. 21. 28. 35.]

Ma trận A sau khi cộng với I6:
[[ 1.  1.  2.  3.  4.  5.]
 [ 6.  8.  8.  9. 10. 11.]
 [12. 13. 15. 15. 16. 17.]
 [18. 19. 20. 22. 22. 23.]
 [24. 25. 26. 27. 29. 29.]
 [30. 31. 32. 33. 34. 36.]]
vecB =
[1. 2. 3. 4. 5. 6.]

C = A × vecB:
[ 71. 198. 325. 452. 579. 706.]

Ma trận D:
[[1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 0. 1. 0.]]

E = A × D.T:
[[ 71.   7.]
 [198.  24.]
 [325.  43.]
 [452.  60.]
 [579.  79.]
 [706.  96.]]

Ma trận F:
[[1. 1.]
 [2. 0.]
 [3. 1.]
 [4. 0.]
 [5. 1.]
 [6. 0.]]

G = A × F:
[[ 71.   7.]
 [198.  24.]
 [325.  43.]
 [452.  60.]
 [579.  79.]
 [706.  96.]]

Ma trận nghịch đả

In [18]:
#4 Bài toán ứng dụng 2 – Tính toán dãy Fibonacci: Con đường tìm đến tỉ số vàng
import numpy as np
A = np.array([[1, 1], [1, 0]])
b = np.array([1, 0])
n = 10
print("Fibonacci:")
print("F(0) = 0")
print("F(1) = 1")
for i in range(n):
    b = A.dot(b)
    print(f"F({i + 2}) = {b[1]}")


Fibonacci:
F(0) = 0
F(1) = 1
F(2) = 1
F(3) = 1
F(4) = 2
F(5) = 3
F(6) = 5
F(7) = 8
F(8) = 13
F(9) = 21
F(10) = 34
F(11) = 55


In [19]:
#5 Đếm số lượng xe vào khu vực trung tâm
import sympy as sp
from sympy import Symbol, solve
x1, x2, x3, x4 = sp.symbols('x1 x2 x3 x4')
pt1 = x4 + 610 - 450 - x1
pt2 = x1 + 400 - x2 - 640
pt3 = x2 + 600 - x3
pt4 = x3 - x4 - 520
# Giải hệ
nghiem = solve((pt1, pt2, pt3, pt4))
print("Nghiệm hệ phương trình:")
print(nghiem)


Nghiệm hệ phương trình:
{x1: x4 + 160, x2: x4 - 80, x3: x4 + 520}


In [21]:
#Bai tap 1
import numpy as np
A1 = np.array([[1, -1], [2, 3]])
B1 = np.array([-2, 6])
nghiem1 = np.linalg.solve(A1, B1)
print("Problem 1 - Giao điểm hai đường thẳng:", nghiem1)
A2 = np.array([[1, -1, 0],
               [2, -1, -1],
               [1, 1, 1]])
B2 = np.array([2, 3, 6])
nghiem2 = np.linalg.solve(A2, B2)
print("Problem 2 - Giao điểm ba mặt phẳng:", nghiem2)
A3 = np.array([[1, 1, 1],
               [4, 2, 1],
               [9, 3, 1]])
B3 = np.array([4, 3, 4])
nghiem3 = np.linalg.solve(A3, B3)
print("Problem 3 - Hệ số đa thức ax² + bx + c:", nghiem3)

A4 = np.array([[1, 0, 1],
               [1, 1, -2],
               [-2, 2, 1]])
B4 = np.array([1, -3, 0])
nghiem4 = np.linalg.solve(A4, B4)
print("Problem 4 - Phân tích phân số: a, b, c =", nghiem4)


Problem 1 - Giao điểm hai đường thẳng: [0. 2.]
Problem 2 - Giao điểm ba mặt phẳng: [3. 1. 2.]
Problem 3 - Hệ số đa thức ax² + bx + c: [ 1. -4.  7.]
Problem 4 - Phân tích phân số: a, b, c = [-0.11 -0.67  1.11]


In [22]:
#Bai tap 2
import sympy as sp
x, y = sp.symbols('x y')
pt1 = x - y + 2
pt2 = 2*x + 3*y - 6
nghiem1 = sp.solve([pt1, pt2], (x, y))
print("Problem 1 - Giao điểm hai đường thẳng:", nghiem1)
x, y, z = sp.symbols('x y z')
pt1 = x - y - 2
pt2 = 2*x - y - z - 3
pt3 = x + y + z - 6
nghiem2 = sp.solve([pt1, pt2, pt3], (x, y, z))
print("Problem 2 - Giao điểm ba mặt phẳng:", nghiem2)
a, b, c = sp.symbols('a b c')
pt1 = a + b + c - 4
pt2 = 4*a + 2*b + c - 3
pt3 = 9*a + 3*b + c - 4
nghiem3 = sp.solve([pt1, pt2, pt3], (a, b, c))
print("Problem 3 - Hệ số đa thức ax² + bx + c:", nghiem3)
a, b, c = sp.symbols('a b c')
pt1 = a + c - 1
pt2 = a + b - 2*c + 3
pt3 = -2*a + 2*b + c
nghiem4 = sp.solve([pt1, pt2, pt3], (a, b, c))
print("Problem 4 - Phân tích phân số:", nghiem4)

Problem 1 - Giao điểm hai đường thẳng: {x: 0, y: 2}
Problem 2 - Giao điểm ba mặt phẳng: {x: 3, y: 1, z: 2}
Problem 3 - Hệ số đa thức ax² + bx + c: {a: 1, b: -4, c: 7}
Problem 4 - Phân tích phân số: {a: -1/9, b: -2/3, c: 10/9}


In [ ]:
#Bai tap 3
import numpy as np
def matrix_power_fibonacci(k):
    F = np.array([[1, 1], [1, 0]])
    result = np.linalg.matrix_power(F, k)
    return result
def fibonacci_up_to(n):
    fib = [0, 1]
    for i in range(2, n + 2):
        fib.append(fib[-1] + fib[-2])
    return fib
k = 5
Fk = matrix_power_fibonacci(k)
print(f"F^{k} =\n", Fk)
fib = fibonacci_up_to(k+1)
print("\nKiểm chứng:")
print("F[k][0][0] = Fib[k+1] =", Fk[0][0], "==", fib[k+1])
print("F[k][0][1] = Fib[k]   =", Fk[0][1], "==", fib[k])
print("F[k][1][0] = Fib[k]   =", Fk[1][0], "==", fib[k])
print("F[k][1][1] = Fib[k-1] =", Fk[1][1], "==", fib[k-1])
