<a href="https://colab.research.google.com/github/HoLeTrungBao/dai_so_tuyen_tinh_ung_dung/blob/main/lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
#bai1
from scipy import linalg
import numpy as np
a = np.array([1, 2, 3])
print("a =", a)
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)])
print("b =\n", b)
c = np.array([[(0.5, 1.5, 10), (3, 2, 1)], [(6, 5, 4), (7, 8, 9)]])
print("c =\n", c)
A = np.matrix(np.random.random((2, 2)))
print("A =\n", A)
B = np.asmatrix(b)
print("B =\n", B)
C = np.asmatrix(np.random.random((10, 5)))
print("C =\n", C)
D = np.asmatrix([[4, 3], [2, 6]])
print("D =\n", D)
F = np.eye(3, k=1)
print("F với k=1:\n", F)
F = np.eye(3, k=0)
print("F với k=0:\n", F)
F = np.eye(3, k=-1)
print("F với k=-1:\n", F)

a = [1 2 3]
b =
 [[1.+9.j 0.+2.j 0.+3.j]
 [0.+4.j 0.+5.j 0.+6.j]]
c =
 [[[ 0.5  1.5 10. ]
  [ 3.   2.   1. ]]

 [[ 6.   5.   4. ]
  [ 7.   8.   9. ]]]
A =
 [[0.26761843 0.66013154]
 [0.60840895 0.20295885]]
B =
 [[1.+9.j 0.+2.j 0.+3.j]
 [0.+4.j 0.+5.j 0.+6.j]]
C =
 [[0.37195754 0.41198242 0.03331871 0.47071737 0.53809151]
 [0.19244117 0.15810754 0.88979018 0.95548265 0.26717254]
 [0.4384168  0.34294376 0.0102302  0.97085726 0.69984046]
 [0.44199943 0.98667119 0.20474554 0.7333359  0.6932839 ]
 [0.45664003 0.39502295 0.68428327 0.34328685 0.21815939]
 [0.17641214 0.97827424 0.7806065  0.88024354 0.28646108]
 [0.02825672 0.53048384 0.03009515 0.61301527 0.28009092]
 [0.14292635 0.50494396 0.69443894 0.4424025  0.82876246]
 [0.3286006  0.91443253 0.01896566 0.7893314  0.69205275]
 [0.07954849 0.61373501 0.87099787 0.81659989 0.05426691]]
D =
 [[4 3]
 [2 6]]
F với k=1:
 [[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
F với k=0:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
F với k=-1:
 [[0. 0. 0.]
 [1. 0. 0.

In [19]:
#bai1.1
from scipy import linalg
import numpy as np

A = np.matrix([[1.0, 2.0], [3.0, 4.0]])
D = np.matrix([[4, 3], [2, 6]])
C = np.asmatrix(np.random.random((10, 5)))
a = np.array([1, 2])
b = np.array([5, 6])
F = np.eye(2)
E = np.asmatrix(a).T

print(np.linalg.matrix_rank(C))
print(A.I)
print(linalg.inv(A))
print(linalg.det(A))
print(A.T)
print(A.H)
print(linalg.solve(A, b))
print(E)
print(linalg.lstsq(F, E))
print(np.add(A, D))
print(np.subtract(A, D))
print(np.divide(A, D))
print(A @ D)
print(np.multiply(D, A))
print(np.dot(A, D))
print(np.vdot(A, D))
print(linalg.expm(A))
print(linalg.logm(A))

5
[[-2.   1. ]
 [ 1.5 -0.5]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0
[[1. 3.]
 [2. 4.]]
[[1. 3.]
 [2. 4.]]
[-4.   4.5]
[[1]
 [2]]
(array([[1.],
       [2.]]), array([], dtype=float64), 2, array([1., 1.]))
[[ 5.  5.]
 [ 5. 10.]]
[[-3. -1.]
 [ 1. -2.]]
[[0.25       0.66666667]
 [1.5        0.66666667]]
[[ 8. 15.]
 [20. 33.]]
[[ 4.  6.]
 [ 6. 24.]]
[[ 8. 15.]
 [20. 33.]]
[[4.]]
[[ 51.9689562   74.73656457]
 [112.10484685 164.07380305]]
[[-0.35043981+2.39111795j  0.92935121-1.09376217j]
 [ 1.39402681-1.64064326j  1.04358699+0.7504747j ]]


In [ ]:
#bai2 Ma trận hội tụ
import numpy as np
# Ma trận phân kỳ A
A = np.array([[0, 1], [1, 0]])
print(A)
temp = A.dot(A)
print(temp)
k = 6
for i in range(k - 1):
    temp = temp.dot(A)
    print(temp)
    print('---')
# Ma trận phân kỳ B
B = np.array([[0, -1], [-1, 0]])
print(B)
temp = B.dot(B)
print(temp)
k = 5
for i in range(k - 1):
    temp = temp.dot(B)
    print(temp)
    print('---')
# Ma trận hội tụ C
C = np.array([[1, 0, 0], [0, 0.5, 1], [0, 0, 0.5]])
print(C)
temp = C.dot(C)
print(temp)
k = 1000
for i in range(k - 1):
    temp = temp.dot(C)
print(temp)
k = 1000
for i in range(k - 1):
    temp = temp.dot(C)
print(temp)


In [ ]:
#Bai 2.4 Ma trận Markov
import numpy as np

# Ma trận M đầu tiên
M = np.array([[0.8, 0.3], [0.2, 0.7]])
MM = M.dot(M)
print("M^2:")
print(MM)
MM = MM.dot(M)
print("M^3:")
print(MM)
for i in range(100):
    MM = MM.dot(M)
print("M^102:")
print(MM)
# Ma trận M thứ hai
M = np.array([[0.5, 0.5], [0.5, 0.5]])
MM = M.dot(M)
print("M^2 (ma trận đồng đều):")
print(MM)
MM = MM.dot(M)
print("M^3 (ma trận đồng đều):")
print(MM)
for i in range(100):
    MM = MM.dot(M)
print("M^102 (ma trận đồng đều):")
print(MM)

In [ ]:
#Bai3
import numpy as np
from scipy import linalg

M = np.array([[0.8, 0.3], [0.2, 0.7]])

P, L, U = linalg.lu(M)

print(P)
print(L)
print(U)

print(L.dot(U))


In [ ]:
#Bai 5
import numpy as np

# Khởi tạo ma trận A (ma trận truyền tin)
A = np.array([
    [0, 1, 0, 1],  # Người 1 gửi cho người 2, 4
    [0, 0, 1, 0],  # Người 2 gửi cho người 3
    [1, 0, 0, 1],  # Người 3 gửi cho người 1, 4
    [1, 1, 0, 0]   # Người 4 gửi cho người 1, 2
])

# Tính A^2
temp = A.dot(A)
print("A^2 (số con đường đi qua 1 trung gian):")
print(temp)

# Tính A^3
temp = temp.dot(A)
print("\nA^3 (số con đường đi qua 2 trung gian):")
print(temp)

# Tính tổng A + A^2 + A^3
sumA = A + A.dot(A) + A.dot(A).dot(A)
print("\nTổng A + A^2 + A^3 (tổng số cách đi qua 0, 1, hoặc 2 trung gian):")
print(sumA)


In [ ]:
#Bài tập chương
#bai1
import numpy as np
def char_to_num(c):
    if c == ' ':
        return 0
    return ord(c.upper()) - ord('A') + 1
def num_to_char(n):
    if n == 0:
        return ' '
    return chr(n - 1 + ord('A'))
def text_to_numbers(text):
    return [char_to_num(c) for c in text]
def numbers_to_text(nums):
    return ''.join(num_to_char(n) for n in nums)
# (a) Chọn ma trận khả nghịch 3x3
K = np.array([
    [2, -1, 0],
    [1, 1, 1],
    [1, 0, 2]
])
try:
    K_inv = np.linalg.inv(K)
    print("Ma trận K khả nghịch, ma trận nghịch đảo là:")
    print(np.round(K_inv, 3))
except np.linalg.LinAlgError:
    print("Ma trận K không khả nghịch, vui lòng chọn ma trận khác.")
    exit()
# (b) Nhập họ tên hoặc mã số sinh viên
text = input("Nhập họ tên hoặc mã số sinh viên (chỉ chữ cái và khoảng trắng): ").strip()
nums = text_to_numbers(text)
while len(nums) % 3 != 0:
    nums.append(0)
# (c) Mã hóa bằng nhân ma trận
encoded_nums = []
for i in range(0, len(nums), 3):
    block = np.array(nums[i:i+3])
    encoded_block = block.dot(K)
    encoded_nums.extend(encoded_block.astype(int))
print("\nDãy số sau khi mã hóa:")
print(encoded_nums)
# (d) Giải mã bằng ma trận nghịch đảo
decoded_nums = []
for i in range(0, len(encoded_nums), 3):
    block = np.array(encoded_nums[i:i+3])
    decoded_block = block.dot(K_inv)
    decoded_block = np.round(decoded_block).astype(int)
    decoded_nums.extend(decoded_block)
decoded_text = numbers_to_text(decoded_nums)

print("\nChuỗi sau khi giải mã (phục hồi):")
print(decoded_text)



In [ ]:
#Bài2
import numpy as np
def char_to_num(c):
    if c == ' ':
        return 0
    return ord(c.upper()) - ord('A') + 1
def num_to_char(n):
    if n == 0:
        return ' '
    return chr(n - 1 + ord('A'))
def text_to_numbers(text):
    return [char_to_num(c) for c in text]
def numbers_to_text(nums):
    return ''.join(num_to_char(n) for n in nums)
# (a) Chọn ma trận 3x3 khả nghịch
K = np.array([
    [2, -1, 0],
    [1, 1, 1],
    [1, 0, 2]
])
# Kiểm tra ma trận khả nghịch
try:
    K_inv = np.linalg.inv(K)
    print("Ma trận K khả nghịch, ma trận nghịch đảo là:")
    print(np.round(K_inv, 3))
except np.linalg.LinAlgError:
    print("Ma trận K không khả nghịch, vui lòng chọn ma trận khác.")
    exit()
# (b) Nhập họ tên hoặc mã số sinh viên
text = input("Nhập họ tên hoặc mã số sinh viên (chỉ chữ cái và khoảng trắng): ").strip()
nums = text_to_numbers(text)
while len(nums) % 3 != 0:
    nums.append(0)
# (c) Mã hóa bằng nhân ma trận
encoded_nums = []
for i in range(0, len(nums), 3):
    block = np.array(nums[i:i+3])
    encoded_block = block.dot(K)
    encoded_nums.extend(encoded_block.astype(int))
print("\nDãy số sau khi mã hóa:")
print(encoded_nums)
# (d) Giải mã bằng ma trận nghịch đảo
decoded_nums = []
for i in range(0, len(encoded_nums), 3):
    block = np.array(encoded_nums[i:i+3])
    decoded_block = block.dot(K_inv)
    decoded_block = np.round(decoded_block).astype(int)
    decoded_nums.extend(decoded_block)
decoded_text = numbers_to_text(decoded_nums)
print("\nChuỗi sau khi giải mã (phục hồi):")
print(decoded_text)
