In [ ]:
#bai 1.1
import numpy as np
D = np.array([[1, 2], [3, 4]])
E = np.empty_like(D) # Define E with the same shape and type as D
try:
    np.copyto(E, D)
except NameError as e:
    print("Lỗi:", e)
print(E)

[[1 2]
 [3 4]]


In [ ]:
#bai 1.2
import numpy as np
x = np.array([['a','b'],['c','d']])
y = 'x'
C = np.array([[x, y], [1, 2]], dtype=object)
print(C)

[[array([['a', 'b'],
         ['c', 'd']], dtype='<U1') 'x']
 [1 2]]


In [ ]:
#bai 2
from numpy import matlib
G = matlib.identity(5)
print("Ma trận G (identity 5x5):")
print(G)
H = matlib.randn(3, 2)
print("\nMa trận H (randn 3x2):")
print(H)
K = matlib.zeros([4, 4])
print("\nMa trận K (zeros 4x4):")
print(K)


Ma trận G (identity 5x5):
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Ma trận H (randn 3x2):
[[-0.47109716 -0.35000926]
 [-0.34721031 -1.34573933]
 [-0.69421785  0.88762946]]

Ma trận K (zeros 4x4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#bai 2.2
import numpy as np
c = [3, 7, 15, 1, 292, 1, 1, 1, 2, 1, 3, 1, 14, 2]
for i in range(len(c)):
    ci = np.asmatrix([[1, 1], [1, 0]])
    ci[0, 0] = c[i]
    if i == 0:
        M = ci
    else:
        M = M @ ci
print("Ma trận kết quả:")
print(M)
approx_pi = M[0, 0] / M[1, 0]
print("\nGiá trị Pi xấp xỉ:")
print(approx_pi)


Ma trận kết quả:
[[165707065  80143857]
 [ 52746197  25510582]]

Giá trị Pi xấp xỉ:
3.1415926535897936


In [ ]:
#bai tap chuong
#bai 1
import numpy as np
from numpy import linalg
def bpcuctieu(a):
    b = []
    o1 = []
    for i in range(len(a)):
        o1.append(1.0)
        b.append(i * 1.0)
    x = np.array([o1, b])
    u = np.dot(x, x.T)
    y = np.array(a)
    u_inv = np.linalg.inv(u)
    v = np.dot(u_inv, x)
    A = np.dot(v, y)
    return A
dulieu = [10.0, 8, 7, 5, 2]
A = bpcuctieu(dulieu)
print("Phương trình tuyến tính: y = {:.1f} + {:.1f} * x".format(A[0], A[1]))

Phương trình tuyến tính: y = 10.2 + -1.9 * x
