In [1]:
#bai 1
import numpy as np
A = np.array([3, -2, 1, 4])
B = np.array([-1, 5, 0, 2])
C = np.array([
    [2, -1, 3],
    [1, 4, -2],
    [0, 2, 5]
])

print("a) Tính A + B và 2A + 3B")
A_plus_B = A + B
linear_combination = 2*A + 3*B
print("A + B =", A_plus_B)
print("2A + 3B =", linear_combination)

print("\nb) Tích vô hướng A · B và góc giữa hai vector")
dot_product = np.dot(A, B)
norm_A = np.linalg.norm(A)
norm_B = np.linalg.norm(B)
cos_theta = dot_product / (norm_A * norm_B)
angle_rad = np.arccos(cos_theta)
angle_deg = np.degrees(angle_rad)
print("A · B =", dot_product)
print("Góc giữa A và B (độ) =", round(angle_deg, 3))

print("\nc) Tính tích ma trận C * C^T")
C_transpose = C.T
C_mul_CT = np.dot(C, C_transpose)
print("C * C^T =\n", C_mul_CT)


a) Tính A + B và 2A + 3B
A + B = [2 3 1 6]
2A + 3B = [ 3 11  2 14]

b) Tích vô hướng A · B và góc giữa hai vector
A · B = -5
Góc giữa A và B (độ) = 99.594

c) Tính tích ma trận C * C^T
C * C^T =
 [[14 -8 13]
 [-8 21 -2]
 [13 -2 29]]


In [2]:
#cau 2
import numpy as np
from numpy.linalg import det, matrix_rank

M = np.array([
    [2, -1, 3, 0],
    [1, 4, -2, 5],
    [0, 2, 6, -3],
    [-1, 0, 1, 4]
])

N = np.array([
    [1, 3, -2, 0],
    [4, -1, 5, 2],
    [0, 2, 3, -1],
    [-3, 1, 0, 4]
])
print("a)")
MN = M @ N
print("M · N =\n", MN)
print("\nb)")
print("det(M) =", round(det(M), 3))
print("\nc)")
print("Rank(N) =", matrix_rank(N))


a)
M · N =
 [[ -2  13   0  -5]
 [  2   0  12  30]
 [ 17   7  28 -14]
 [-13   3   5  15]]

b)
det(M) = 409.0

c)
Rank(N) = 4


In [3]:
#cau 3
import numpy as np
from numpy.linalg import inv, det

P = np.array([
    [3, -1, 0, 2],
    [1, 4, -2, 0],
    [0, 1, 5, -1],
    [2, 0, 1, 3]
])
b = np.array([6, 8, 3, 7])
print("a)")
if det(P) != 0:
    P_inv = inv(P)
    print("P^(-1) =\n", np.round(P_inv, 3))
else:
    print("Ma trận không khả nghịch")
print("\nb)")
x = P_inv @ b
print("Nghiệm x =", np.round(x, 3))
print("\nc)")
print("P · x =", np.round(P @ x, 3))
print("b =", b)


a)
P^(-1) =
 [[ 0.5    0.1    0.1   -0.3  ]
 [-0.143  0.2    0.057  0.114]
 [-0.036 -0.05   0.164  0.079]
 [-0.321 -0.05  -0.121  0.507]]

b)
Nghiệm x = [2.    1.714 0.429 0.857]

c)
P · x = [6. 8. 3. 7.]
b = [6 8 3 7]


In [4]:
#cau 4
import numpy as np
from numpy.linalg import eig, norm

Q = np.array([
    [5, -2, 1],
    [0, 3, -1],
    [2, 0, 4]
])
print("a)")
eigvals = np.linalg.eigvals(Q)
print("Giá trị riêng:", np.round(eigvals, 3))
print("\nb)")
vals, vecs = eig(Q)
print("Vector riêng:\n", np.round(vecs, 3))
print("\nc)")
for i, v in enumerate(vecs.T):
    v_norm = v / norm(v)
    print(f"v{i+1} =", np.round(v_norm, 3))


a)
Giá trị riêng: [6.355+0.j    2.822+1.077j 2.822-1.077j]

b)
Vector riêng:
 [[ 0.748+0.j    -0.374+0.342j -0.374-0.342j]
 [-0.189+0.j     0.095+0.574j  0.095-0.574j]
 [ 0.636+0.j     0.636+0.j     0.636-0.j   ]]

c)
v1 = [ 0.748+0.j -0.189+0.j  0.636+0.j]
v2 = [-0.374+0.342j  0.095+0.574j  0.636+0.j   ]
v3 = [-0.374-0.342j  0.095-0.574j  0.636-0.j   ]


In [6]:
#cau 5
import numpy as np
from numpy.linalg import inv, norm, det

R = np.array([
    [4, -1, 2],
    [1, 3, -2],
    [0, 2, 5]
])
b = np.array([12, 5, 9])
print("a)")
x1 = np.linalg.solve(R, b)
print("Nghiệm x1 =", x1)
print("\nb)")
if det(R) != 0:
    R_inv = inv(R)
    x2 = R_inv @ b
    print("R khả nghịch. Nghịch đảo R:\n", np.round(R_inv, 3))
    print("Nghiệm x2 =", np.round(x2, 3))
    print("So sánh: x1 == x2?", np.allclose(x1, x2))
else:
    print("R không khả nghịch.")
print("\nc)")
fro_norm = norm(R, 'fro')
print("Frobenius norm =", round(fro_norm, 3))


a)
Nghiệm x1 = [2.78823529 1.52941176 1.18823529]

b)
R khả nghịch. Nghịch đảo R:
 [[ 0.224  0.106 -0.047]
 [-0.059  0.235  0.118]
 [ 0.024 -0.094  0.153]]
Nghiệm x2 = [2.788 1.529 1.188]
So sánh: x1 == x2? True

c)
Frobenius norm = 8.0
