In [2]:
#bai 2
import numpy as np
A = np.array([2, -1.3, 0])
B = np.array([1, 4, -2.5])
C = np.array([[1, 2, -1],
              [0, 3, 4],
              [2, -1, 0]])
# a) Tính A + B và 3A - 2B
sum_AB = A + B
scalar_expr = 3 * A - 2 * B
print("a) A + B =", sum_AB)
print("   3A - 2B =", scalar_expr)
# b) Tính tích vô hướng A · B và góc giữa hai vector
dot_product = np.dot(A, B)
norm_A = np.linalg.norm(A)
norm_B = np.linalg.norm(B)
cos_theta = dot_product / (norm_A * norm_B)
theta_rad = np.arccos(cos_theta)
theta_deg = np.degrees(theta_rad)
print("b) A · B =", dot_product)
print("   Góc giữa A và B (độ) =", round(theta_deg, 3))
# c) Tính C^T C
CtC = np.dot(C.T, C)
print("c) C^T C =\n", CtC)


a) A + B = [ 3.   2.7 -2.5]
   3A - 2B = [  4.  -11.9   5. ]
b) A · B = -3.2
   Góc giữa A và B (độ) = 106.154
c) C^T C =
 [[ 5  0 -1]
 [ 0 14 10]
 [-1 10 17]]


In [3]:
#bai 2
import numpy as np
M = np.array([
    [1, 2, 3, 0],
    [4, 5, 6, 1],
    [7, 8, 9, 2],
    [0, 1, 1, 0]
])
N = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11],
    [12, 13, 14, 15]
])
# a) Tính tích M × N
product_MN = np.dot(M, N)
print("a) Tích M × N =\n", product_MN)
# b) Tính định thức của M
try:
    det_M = np.linalg.det(M)
    print("\nb) Định thức của M =", round(det_M, 3))
except np.linalg.LinAlgError as e:
    print("\nb) Không thể tính định thức vì:", e)
# c) Tính hạng của ma trận N
rank_N = np.linalg.matrix_rank(N)
print("\nc) Hạng của N =", rank_N)


a) Tích M × N =
 [[ 32  38  44  50]
 [ 80  96 112 128]
 [128 154 180 206]
 [ 12  14  16  18]]

b) Định thức của M = 0.0

c) Hạng của N = 2


In [4]:
#bai 3
import numpy as np
P = np.array([
    [2, 1, 0, 1],
    [0, 3, 1, -1],
    [1, 0, 4, 2],
    [0, 1, 0, 3]
])
b = np.array([4, 7, 9, 5])  # Vector hệ số bên phải của hệ phương trình
# a) Tìm ma trận nghịch đảo của P
try:
    P_inv = np.linalg.inv(P)
    print("a) Ma trận nghịch đảo của P:\n", P_inv)
except np.linalg.LinAlgError:
    print("a) Ma trận P không khả nghịch (không tồn tại ma trận nghịch đảo).")
# b) Giải hệ phương trình P * x = b bằng nghịch đảo ma trận
x = np.dot(P_inv, b)
print("\nb) Nghiệm của hệ phương trình là:\n", x)
# c) Kiểm tra nghiệm: P * x có bằng b không?
b_check = np.dot(P, x)
print("\nc) Kiểm tra lại: P * x =\n", b_check)
print("   So với vector b ban đầu:\n", b)


a) Ma trận nghịch đảo của P:
 [[ 0.48837209 -0.09302326  0.02325581 -0.20930233]
 [ 0.03488372  0.27906977 -0.06976744  0.12790698]
 [-0.11627907  0.06976744  0.23255814 -0.09302326]
 [-0.01162791 -0.09302326  0.02325581  0.29069767]]

b) Nghiệm của hệ phương trình là:
 [0.46511628 2.10465116 1.65116279 0.96511628]

c) Kiểm tra lại: P * x =
 [4. 7. 9. 5.]
   So với vector b ban đầu:
 [4 7 9 5]


In [10]:
#bai 4
import numpy as np
Q = np.array([[4, -1, 0],
              [1, 3, -2],
              [0, 1, 2]])

# a) Tìm giá trị riêng của Q
eigenvalues = np.linalg.eigvals(Q)
print("a) Giá trị riêng của Q:", eigenvalues)
# b) Tìm vector riêng tương ứng
eigenvalues, eigenvectors = np.linalg.eig(Q)
print("\nb) Vector riêng tương ứng:")
for i in range(len(eigenvalues)):
    print(f"Giá trị riêng {eigenvalues[i]}: {eigenvectors[:, i]}")
# c) Chuẩn hóa vector riêng (vector đơn vị)
normalized_vectors = []
for vector in eigenvectors.T:
    norm = np.linalg.norm(vector)
    normalized_vector = vector / norm
    normalized_vectors.append(normalized_vector)
print("\nc) Vector riêng chuẩn hóa:")
for i, vec in enumerate(normalized_vectors):
    print(f"Vector riêng {i+1} chuẩn hóa: {vec}")


a) Giá trị riêng của Q: [3.45339765+0.j         2.77330117+1.46771151j 2.77330117-1.46771151j]

b) Vector riêng tương ứng:
Giá trị riêng (3.4533976515164015+0j): [0.83327121+0.j 0.455468  +0.j 0.31338154+0.j]
Giá trị riêng (2.773301174241798+1.4677115087102246j): [-0.26206044-0.31354813j -0.78166743+0.j         -0.21963176+0.41685708j]
Giá trị riêng (2.773301174241798-1.4677115087102246j): [-0.26206044+0.31354813j -0.78166743-0.j         -0.21963176-0.41685708j]

c) Vector riêng chuẩn hóa:
Vector riêng 1 chuẩn hóa: [0.83327121+0.j 0.455468  +0.j 0.31338154+0.j]
Vector riêng 2 chuẩn hóa: [-0.26206044-0.31354813j -0.78166743+0.j         -0.21963176+0.41685708j]
Vector riêng 3 chuẩn hóa: [-0.26206044+0.31354813j -0.78166743+0.j         -0.21963176-0.41685708j]


In [14]:
#bai 5
import numpy as np
R = np.array([[1, -2, 3], [0, 1, 4], [-1, 1, -1]])
b = np.array([10, 8, 7])
z = np.linalg.solve(R, b)
print("a) Giải hệ phương trình Rz = b: z =", z)
det_R = np.linalg.det(R)
is_invertible = det_R != 0
print("\nb) Ma trận R có khả nghịch không? (True/False):", is_invertible)
if is_invertible:
    print("Nghịch đảo của ma trận R:")
    R_inv = np.linalg.inv(R)
    print(R_inv)
frobenius_norm = np.linalg.norm(R, 'fro')
print("\nc) Chuỗi Frobenius của ma trận R:", frobenius_norm)

a) Giải hệ phương trình Rz = b: z = [-19.83333333  -8.66666667   4.16666667]

b) Ma trận R có khả nghịch không? (True/False): True
Nghịch đảo của ma trận R:
[[-0.83333333  0.16666667 -1.83333333]
 [-0.66666667  0.33333333 -0.66666667]
 [ 0.16666667  0.16666667  0.16666667]]

c) Chuỗi Frobenius của ma trận R: 5.830951894845301
